# Generated by Django 2.0.3 on 2018-03-15 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=10)),
                ('ciudad', models.CharField(choices=[('CB', 'Cordoba'), ('CP', 'Carlos Paz'), ('VM', 'Villa Maria'), ('RT', 'Rio Tercero'), ('RC', 'Rio Cuarto')], max_length=2)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=100)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionProducto',
            fields=[
                ('producto_desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Compra')),
                ('producto_desc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.DescripcionProducto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('material', models.CharField(choices=[('Pl', 'Plastico'), ('Ma', 'Madera'), ('Cr', 'Cristal'), ('Cu', 'Cuero')], max_length=2)),
                ('color', models.CharField(choices=[('N', 'Negro'), ('B', 'Blanco'), ('R', 'Rojo'), ('V', 'Verde'), ('A', 'Azul')], max_length=1)),
                ('largo', models.IntegerField(default=0)),
                ('ancho', models.IntegerField(default=0)),
                ('alto', models.IntegerField(default=0)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='descripcionproducto',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
