# Generated by Django 2.0.3 on 2018-03-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcionproducto',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto_desc_id',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='aaaaaaaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='aaaaa', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='DescripcionProducto',
        ),
    ]
